version: '3'

services:
    postgres:
      image: postgres:alpine
      container_name: postgres
      environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
      ports:
        - 5432:5432
      restart: always